### ISSUE TITLE
[AI Studios] Todo List

### ISSUE THREAD

**Issue by deepbig** [deepbig/lulluland#57]
- [ ] SDK 적용 (initializing = get started button)
- [ ] Select Langauge (en, ko, zh)
- [ ] Select Model (zh: Shaosuki, en: Jonadan, jp: Mizuki, ko: yoon sung young)
- [ ] select Clothes (jp has multiple colors)
- [ ] type texts for making video
- [ ] loading
- [ ] show video and let user download video
